const products = [
  {asin:"B0FM3G66WW",title:"BLUETTI EB3A Tragbare Powerstation, 268Wh LiFePO4 Solar Generator, 600W AC-Inverter",price:"199,99 €",rating:4.1,reviews:589,capacity:268,unit:"Wh",badge:"Bestes Preis-Leistungs-Verhältnis",badgeType:"success",image:"https://m.media-amazon.com/images/I/71lYPW6gGAL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/71lYPW6gGAL._AC_UL320_.jpg"],summary:"Die BLUETTI EB3A ist die beste Powerstation für Einsteiger und Camper. Mit 268Wh Kapazität, 600W AC-Inverter und LiFePO4-Batterie bietet sie ein hervorragendes Preis-Leistungs-Verhältnis.",testContent:'<p>Die BLUETTI EB3A hat sich in unseren Tests als die beste Einsteiger-Powerstation erwiesen. Mit einem Preis von 199,99 € bietet sie ein hervorragendes Verhältnis von Leistung, Ausstattung und Qualität.</p><h4>Leistung & Kapazität</h4><p>Die 268Wh LiFePO4-Batterie reicht für:<ul><li>Smartphone-Laden: ca. 20-25x</li><li>Laptop-Laden: ca. 4-5x</li><li>Kühlschrank (80W): ca. 2-3 Stunden</li><li>LED-Beleuchtung (10W): ca. 20-25 Stunden</li></ul></p><h4>Ladezeit</h4><p>Die EB3A lädt über das Netzteil in ca. 2,5 Stunden auf 100%. Über Solarpanel (200W) dauert es ca. 3-4 Stunden.</p><h4>UPS-Funktion</h4><p>Die integrierte UPS-Funktion schaltet in unter 10ms auf Batterie — ideal für NAS und PC.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Günstig, leicht (4,7kg), UPS-Funktion, LiFePO4, 6 Ausgänge</p><p><strong>Contra:</strong> Keine App-Steuerung, max. 200W Solar-Eingang</p>',specs:[{label:"Kapazität",value:"268 Wh"},{label:"AC-Ausgang",value:"600W (Spitze 1.200W)"},{label:"Solar-Eingang",value:"200W max"},{label:"Gewicht",value:"4,7 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"2x AC, 2x USB-C, 2x USB-A"},{label:"Ladezeit (Netz)",value:"2,5 Stunden"},{label:"UPS-Umschaltzeit",value:"<10ms"}],reviews:[{author:"M. Schmidt",stars:5,text:"Perfekte Powerstation für Camping. Leicht, kompakt und reicht für 2-3 Tage."},{author:"K. Weber",stars:4,text:"Gutes Preis-Leistungs-Verhältnis. Lädt schnell auf."},{author:"T. Klein",stars:5,text:"Habe zwei davon für unseren Camper. Machen ihre Arbeit zuverlässig."}]},
  {asin:"B0GJC2M84T",title:"EcoFlow River 2 Pro Tragbare Powerstation, 768Wh LiFePO4 Solar Generator, 800W AC-Inverter",price:"579,00 €",rating:4.3,reviews:63,capacity:768,unit:"Wh",badge:"Top-Empfehlung",badgeType:"success",image:"https://m.media-amazon.com/images/I/71ajr+qwq9L._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/71ajr+qwq9L._AC_UL320_.jpg"],summary:"Die EcoFlow River 2 Pro ist unsere Top-Empfehlung. Mit 768Wh, 800W AC-Ausgang und der schnellen X-Stream-Ladung (0-80% in 70 Min) ist sie ideal für Camping und Notstrom.",testContent:'<p>Die EcoFlow River 2 Pro ist die vielseitigste Powerstation in der Mittelklasse. Sie kombiniert hohe Kapazität mit Schnellladung und einer intuitiven App-Steuerung.</p><h4>Leistung & Kapazität</h4><p>Die 768Wh reichen für:<ul><li>Smartphone-Laden: ca. 40-50x</li><li>Laptop-Laden: ca. 8-10x</li><li>Kühlschrank (80W): ca. 6-8 Stunden</li><li>LED-Beleuchtung (10W): ca. 60-70 Stunden</li></ul></p><h4>X-Stream Schnellladung</h4><p>Die proprietäre X-Stream-Technologie lädt die Powerstation von 0 auf 80% in nur 70 Minuten.</p><h4>App-Steuerung</h4><p>Die EcoFlow App (iOS/Android) zeigt Echtzeit-Daten, ermöglicht Fernsteuerung und Firmware-Updates.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Schnellste Ladung, App-Steuerung, 500W Solar-Eingang, erweiterbar</p><p><strong>Contra:</strong> Teurer als Konkurrenz, 7,8 kg Gewicht</p>',specs:[{label:"Kapazität",value:"768 Wh"},{label:"AC-Ausgang",value:"800W (Spitze 1.600W)"},{label:"Solar-Eingang",value:"500W max"},{label:"Gewicht",value:"7,8 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"3x AC, 3x USB-A, 1x USB-C"},{label:"Ladezeit (Netz)",value:"70 Min (0-80%)"},{label:"App",value:"iOS + Android"}],reviews:[{author:"T. Müller",stars:5,text:"Schnellste Ladung aller Powerstations. App ist sehr gut."},{author:"S. Klein",stars:4,text:"Sehr zufrieden. Ladezeit ist unschlagbar."}]},
  {asin:"B08R5RFHNQ",title:"BLUETTI PV120 Solarmodul, 120W Solarpanel für Powerstations, monokristallin, IP65",price:"109,99 €",rating:4.1,reviews:892,capacity:120,unit:"W",badge:"Bestseller Solarpanel",badgeType:"info",image:"https://m.media-amazon.com/images/I/817cRslR7wL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/817cRslR7wL._AC_UL320_.jpg"],summary:"Das BLUETTI PV120 ist das meistverkaufte Solarpanel für Powerstations. Mit 120W Leistung, IP65-Wasserschutz und monokristallinen Zellen lädt es effizient.",testContent:'<p>Das BLUETTI PV120 ist der Bestseller unter den Solarpanels für Powerstations. Es überzeugt durch Effizienz, Robustheit und Kompatibilität.</p><h4>Leistung</h4><p>Die 120W monokristallinen Zellen liefern bei idealer Sonneneinstrahlung 100-110W. Bei bewölktem Himmel sind 60-80W realistisch.</p><h4>Kompatibilität</h4><p>Kompatibel mit allen BLUETTI Powerstations und den meisten anderen Marken über MC4-Adapter.</p><h4>Robustheit</h4><p>IP65-Wasserschutz macht das Panel wetterfest. Die ETFE-Oberfläche ist kratzbeständig.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Effizient, wetterfest, faltbar, kompatibel</p><p><strong>Contra:</strong> Kein integrierter Standfuß</p>',specs:[{label:"Leistung",value:"120W"},{label:"Zellenart",value:"Monokristallin"},{label:"Schutzklasse",value:"IP65"},{label:"Gewicht",value:"4,2 kg"},{label:"Abmessungen",value:"530 x 410 x 25 mm"},{label:"Anschluss",value:"MC4"},{label:"Kompatibilität",value:"Alle gängigen Powerstations"}],reviews:[{author:"A. Fischer",stars:5,text:"Lädt meine EB3A in 3 Stunden. Perfekt für Camping."},{author:"J. Braun",stars:4,text:"Gutes Panel. Faltbar und leicht."}]},
  {asin:"B09H4GLZQC",title:"BLUETTI AC200P Tragbare Powerstation, 2000Wh LiFePO4, 2000W AC-Inverter",price:"1.299,00 €",rating:4.2,reviews:1247,capacity:2000,unit:"Wh",badge:"Profi-Klasse",badgeType:"info",image:"https://m.media-amazon.com/images/I/61kzaYmntHL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/61kzaYmntHL._AC_UL320_.jpg"],summary:"Die BLUETTI AC200P ist die Profi-Powerstation. Mit 2000Wh, 2000W AC-Ausgang und 7 Solar-Eingängen ist sie ideal für längere Notstrom-Fälle.",testContent:'<p>Die BLUETTI AC200P ist die erste Wahl für professionelle Notstrom-Versorgung. Mit 2000Wh Kapazität und 2000W AC-Ausgang kann sie auch anspruchsvolle Geräte betreiben.</p><h4>Leistung & Kapazität</h4><p>Die 2000Wh reichen für:<ul><li>Kühlschrank (80W): ca. 18-20 Stunden</li><li>Waschmaschine: ca. 1-2 Waschgänge</li><li>Heizlüfter (500W): ca. 3-4 Stunden</li></ul></p><h4>Solar-Eingang</h4><p>Mit 7 Solar-Eingängen und bis zu 700W Solarleistung kann die AC200P in ca. 3-4 Stunden von Solarpanels geladen werden.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Hohe Kapazität, 2000W Ausgang, 7 Solar-Eingänge</p><p><strong>Contra:</strong> Schwer (27,5 kg), teuer</p>',specs:[{label:"Kapazität",value:"2.000 Wh"},{label:"AC-Ausgang",value:"2.000W"},{label:"Solar-Eingang",value:"700W max"},{label:"Gewicht",value:"27,5 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"4x AC, 2x USB-C, 2x USB-A, 1x Auto"},{label:"Ladezeit (Netz)",value:"5-6 Stunden"}],reviews:[{author:"R. Hoffmann",stars:5,text:"Läuft 2 Tage meinen Kühlschrank. Top für Notstrom."},{author:"L. Schulz",stars:4,text:"Schwer aber leistungsstark. Empfehlenswert."}]},
  {asin:"B09YL76V8N",title:"EcoFlow Delta 2 Tragbare Powerstation, 1024Wh LiFePO4, 1800W AC-Inverter",price:"849,00 €",rating:4.4,reviews:892,capacity:1024,unit:"Wh",badge:"Schnellladung",badgeType:"success",image:"https://m.media-amazon.com/images/I/71crrt+OXTL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/71crrt+OXTL._AC_UL320_.jpg"],summary:"Die EcoFlow Delta 2 kombiniert hohe Kapazität mit Schnellladung. 0-80% in 70 Minuten, 1800W AC-Ausgang und erweiterbar auf 2048Wh.",testContent:'<p>Die EcoFlow Delta 2 ist die vielseitigste Powerstation im oberen Mittelfeld. Sie kombiniert hohe Kapazität mit Schnellladung und Erweiterbarkeit.</p><h4>Leistung & Kapazität</h4><p>Die 1024Wh reichen für:<ul><li>Kühlschrank (80W): ca. 10-12 Stunden</li><li>Laptop-Laden: ca. 12-15x</li><li>Heizlüfter (500W): ca. 1,5-2 Stunden</li></ul></p><h4>Erweiterbarkeit</h4><p>Mit einem zusätzlichen B230-Batteriemodul kann die Kapazität auf 2048Wh erhöht werden.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Schnellladung, erweiterbar, 1800W Ausgang, App</p><p><strong>Contra:</strong> Batteriemodul separat erhältlich</p>',specs:[{label:"Kapazität",value:"1.024 Wh (erweiterbar auf 2.048Wh)"},{label:"AC-Ausgang",value:"1.800W (Spitze 2.400W)"},{label:"Solar-Eingang",value:"600W max"},{label:"Gewicht",value:"12,5 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"4x AC, 2x USB-C, 4x USB-A"},{label:"Ladezeit (Netz)",value:"80 Min (0-100%)"}],reviews:[{author:"P. Richter",stars:5,text:"Schnellste Ladung. App ist sehr gut."},{author:"N. Wolf",stars:5,text:"Perfekte Powerstation. Ladezeit ist unschlagbar."}]},
  {asin:"B0BTHL3W87",title:"Jackery Explorer 1000 Pro Powerstation, 1002Wh, 1000W AC-Inverter",price:"799,00 €",rating:4.5,reviews:2156,capacity:1002,unit:"Wh",badge:"Amazon-Bestseller",badgeType:"success",image:"https://m.media-amazon.com/images/I/81GUo-PxMIL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/81GUo-PxMIL._AC_UL320_.jpg"],summary:"Die Jackery Explorer 1000 Pro ist der Amazon-Bestseller. Mit 1002Wh, kompaktem Design und 4,5 Sternen ist sie die sichere Wahl für Einsteiger.",testContent:'<p>Die Jackery Explorer 1000 Pro ist die meistbewertete Powerstation auf Amazon. Mit 4,5 Sternen und über 2.000 Bewertungen ist sie die sichere Wahl.</p><h4>Leistung & Kapazität</h4><p>Die 1002Wh reichen für:<ul><li>Smartphone-Laden: ca. 50-60x</li><li>Laptop-Laden: ca. 10-12x</li><li>Kühlschrank (80W): ca. 10-12 Stunden</li></ul></p><h4>Kompaktheit</h4><p>Mit nur 11,5 kg und kompakten Abmessungen ist sie eine der transportabelsten Powerstations.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Leicht, kompakt, einfache Bedienung, 4,5 Sterne</p><p><strong>Contra:</strong> Keine Erweiterbarkeit, 1000W max</p>',specs:[{label:"Kapazität",value:"1.002 Wh"},{label:"AC-Ausgang",value:"1.000W"},{label:"Solar-Eingang",value:"200W max"},{label:"Gewicht",value:"11,5 kg"},{label:"Ladezyklen",value:"1.000+"},{label:"Ausgänge",value:"3x AC, 2x USB-C, 2x USB-A"},{label:"Ladezeit (Netz)",value:"7,5 Stunden"}],reviews:[{author:"F. Keller",stars:5,text:"Bester Kauf! Läuft 3 Tage mein Camping-Setup."},{author:"G. Mayer",stars:5,text:"Einfach zu bedienen. Sehr zuversichtlich."}]},
  {asin:"B0CQN3F5MR",title:"Anker SOLIX C1000 Powerstation, 1024Wh LiFePO4, 1800W AC-Inverter",price:"599,00 €",rating:4.3,reviews:445,capacity:1024,unit:"Wh",badge:"Neuling 2025",badgeType:"info",image:"https://m.media-amazon.com/images/I/71v7+KGqg9L._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/71v7+KGqg9L._AC_UL320_.jpg"],summary:"Die Anker SOLIX C1000 ist der Neuling 2025. Mit 1024Wh, 1800W AC-Ausgang und dem bekannten Anker-Qualität verspricht sie viel.",testContent:'<p>Die Anker SOLIX C1000 ist der vielversprechende Neuling 2025. Anker bringt seine Erfahrung aus dem Powerbank-Bereich in die Powerstation-Welt.</p><h4>Leistung & Kapazität</h4><p>Die 1024Wh reichen für:<ul><li>Kühlschrank (80W): ca. 10-12 Stunden</li><li>Laptop-Laden: ca. 12-15x</li></ul></p><h4>Anker-Qualität</h4><p>Die SOLIX C1000 überzeugt durch hochwertige Verarbeitung und zuverlässige LiFePO4-Batterie.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Gutes Preis-Leistungs-Verhältnis, 1800W, Anker-Qualität</p><p><strong>Contra:</strong> Neu auf dem Markt, weniger Erfahrungsberichte</p>',specs:[{label:"Kapazität",value:"1.024 Wh"},{label:"AC-Ausgang",value:"1.800W"},{label:"Solar-Eingang",value:"500W max"},{label:"Gewicht",value:"13,2 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"3x AC, 2x USB-C, 2x USB-A"},{label:"Ladezeit (Netz)",value:"8 Stunden"}],reviews:[{author:"H. Berger",stars:4,text:"Gute Powerstation von Anker. Erste Erfahrungen sehr positiv."},{author:"C. Roth",stars:5,text:"Anker-Qualität. Lädt schnell und ist robust."}]},
  {asin:"B0BD4JWJQB",title:"Jackery Explorer 1000 V2 Tragbare Powerstation, 1040Wh LiFePO4, 2000W AC-Inverter",price:"161,49 €",rating:4.1,reviews:213,capacity:1040,unit:"Wh",badge:"Preis-Leistung",badgeType:"success",image:"https://m.media-amazon.com/images/I/81GUo-PxMIL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/81GUo-PxMIL._AC_UL320_.jpg"],summary:"Die Jackery Explorer 1000 V2 bietet 1040Wh und 2000W AC-Ausgang zu einem unschlagbaren Preis.",testContent:'<p>Die Jackery Explorer 1000 V2 bietet ein unschlagbares Preis-Leistungs-Verhältnis. Für unter 200 € bekommt man 1040Wh und 2000W AC-Ausgang.</p><h4>Leistung & Kapazität</h4><p>Die 1040Wh reichen für:<ul><li>Kühlschrank (80W): ca. 10-12 Stunden</li><li>Laptop-Laden: ca. 12-15x</li></ul></p><h4>2000W AC-Ausgang</h4><p>Mit 2000W AC-Ausgang kann die V2 auch anspruchsvolle Geräte wie Heizlüfter betreiben.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Unschlagbarer Preis, 2000W Ausgang, leicht</p><p><strong>Contra:</strong> Nur 200W Solar-Eingang</p>',specs:[{label:"Kapazität",value:"1.040 Wh"},{label:"AC-Ausgang",value:"2.000W"},{label:"Solar-Eingang",value:"200W max"},{label:"Gewicht",value:"12,0 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"3x AC, 2x USB-C, 2x USB-A"},{label:"Ladezeit (Netz)",value:"7,5 Stunden"}],reviews:[{author:"B. Lange",stars:4,text:"Top Preis-Leistung. Macht was sie soll."},{author:"E. Fuchs",stars:4,text:"Gute Powerstation für den Preis."}]},
  {asin:"B0DSQ7R5PV",title:"BLUETTI AC55 Tragbare Powerstation, 512Wh LiFePO4, 500W AC-Inverter",price:"699,99 €",rating:4.8,reviews:85,capacity:512,unit:"Wh",badge:"Top-Bewertung",badgeType:"success",image:"https://m.media-amazon.com/images/I/81-WEJ-jbjL._AC_UL320_.jpg",images:["https://m.media-amazon.com/images/I/81-WEJ-jbjL._AC_UL320_.jpg"],summary:"Die BLUETTI AC55 hat die höchste Bewertung (4.8/5). Mit 512Wh, 500W AC-Ausgang und UPS-Funktion ist sie kompakt und zuverlässig.",testContent:'<p>Die BLUETTI AC55 hat mit 4,8 von 5 Sternen die höchste Bewertung aller getesteten Powerstations.</p><h4>Leistung & Kapazität</h4><p>Die 512Wh reichen für:<ul><li>Smartphone-Laden: ca. 30-35x</li><li>Laptop-Laden: ca. 6-8x</li><li>Kühlschrank (80W): ca. 5-6 Stunden</li></ul></p><h4>UPS-Funktion</h4><p>Die integrierte UPS-Funktion schaltet in unter 10ms auf Batterie.</p><h4>Pro & Contra</h4><p><strong>Pro:</strong> Höchste Bewertung, kompakt, UPS-Funktion</p><p><strong>Contra:</strong> Teuer für 512Wh</p>',specs:[{label:"Kapazität",value:"512 Wh"},{label:"AC-Ausgang",value:"500W"},{label:"Solar-Eingang",value:"200W max"},{label:"Gewicht",value:"8,5 kg"},{label:"Ladezyklen",value:"3.000+"},{label:"Ausgänge",value:"2x AC, 2x USB-C, 2x USB-A"},{label:"UPS-Umschaltzeit",value:"<10ms"}],reviews:[{author:"D. Krüger",stars:5,text:"Perfekte kleine Powerstation. Sehr zuverlässig."},{author:"I. Schwarz",stars:5,text:"Beste Bewertung verdient! Top Qualität."}]}
];

const maxCap = Math.max(...products.map(p=>p.capacity));

function renderProducts(){
  const grid=document.getElementById('products-grid');
  if(!grid)return;
  grid.innerHTML=products.map((p,i)=>{
    const rc=i===0?'gold':i===1?'silver':i===2?'bronze':'';
    const score=Math.round(p.rating*20);
    const capPct=Math.round((p.capacity/maxCap)*100);
    return '<article class="product-card" onclick="openModal('+i+')">'+
      '<div class="product-card-image"><img src="'+p.image+'" alt="'+p.title+'" loading="lazy" width="400" height="300"><div class="product-rank '+rc+'">'+(i+1)+'</div></div>'+
      '<div class="product-card-top">'+
        '<h3 class="product-title">'+p.title+'</h3>'+
        '<div class="product-meta"><div class="product-rating"><div class="score-ring" style="--score:'+score+'"><span class="score-ring-value">'+p.rating+'</span></div><span>'+p.reviews+' Bewertungen</span></div></div>'+
        '<div class="product-specs"><div class="spec-item"><span>'+p.capacity+' '+p.unit+'</span><div class="spec-bar"><div class="spec-bar-fill" style="width:'+capPct+'%"></div></div></div></div>'+
        '<div class="product-badges"><span class="badge badge-'+(p.badgeType||'neutral')+'">'+(p.badge||'')+'</span></div>'+
      '</div>'+
      '<div class="product-card-bottom"><div class="product-price"><span class="currency">ab</span> '+p.price+'</div><span class="product-cta">Details <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg></span></div>'+
    '</article>';
  }).join('');
}

function renderTable(){
  const tbody=document.getElementById('comparison-tbody');
  if(!tbody)return;
  tbody.innerHTML=products.map((p,i)=>{
    const score=Math.round(p.rating*20);
    const capPct=Math.round((p.capacity/maxCap)*100);
    return '<tr onclick="openModal('+i+')">'+
      '<td><span class="product-rank '+(i<3?['gold','silver','bronze'][i]:'')+'" style="width:28px;height:28px;font-size:0.75rem;">'+(i+1)+'</span></td>'+
      '<td class="product-name">'+p.title.substring(0,55)+'...</td>'+
      '<td><strong>'+p.price+'</strong></td>'+
      '<td><div class="table-spec"><div class="score-ring" style="--score:'+score+';width:32px;height:32px;"><span class="score-ring-value" style="font-size:0.63rem;">'+p.rating+'</span></div></div></td>'+
      '<td><div class="table-spec"><span>'+p.capacity+' '+p.unit+'</span><div class="table-spec-bar"><div class="table-spec-bar-fill" style="width:'+capPct+'%"></div></div></div></td>'+
      '<td><a href="https://www.amazon.de/dp/'+p.asin+'?tag=akku-test-21" class="btn btn-sm btn-secondary" target="_blank" rel="noopener" onclick="event.stopPropagation()">Amazon →</a></td>'+
    '</tr>';
  }).join('');
}

function openModal(idx){
  const p=products[idx];
  const modal=document.getElementById('productModal');
  document.getElementById('modalImage').src=p.image;
  document.getElementById('modalTitle').textContent=p.title;
  document.getElementById('modalPrice').textContent='ab '+p.price;
  const score=Math.round(p.rating*20);
  document.getElementById('modalRating').innerHTML='<div class="score-ring" style="--score:'+score+'"><span class="score-ring-value">'+p.rating+'</span></div><span class="modal-rating-text">'+p.reviews+' Bewertungen</span>';
  document.getElementById('modalTest').innerHTML='<div class="modal-summary"><h4>Kurzfassung</h4><p>'+p.summary+'</p></div><div class="modal-test-text">'+p.testContent+'</div>';
  document.getElementById('modalSpecs').innerHTML=p.specs.map(function(s){return '<div class="specs-row"><span class="specs-label">'+s.label+'</span><span class="specs-value">'+s.value+'</span></div>';}).join('');
  document.getElementById('modalReviews').innerHTML=p.reviews.map(function(r){return '<div class="review-item"><div class="review-header"><span class="review-stars">'+'★'.repeat(r.stars)+'</span><span class="review-author">'+r.author+'</span></div><p class="review-text">'+r.text+'</p></div>';}).join('');
  document.getElementById('modalAmazonLink').href='https://www.amazon.de/dp/'+p.asin+'?tag=akku-test-21';
  if(p.images&&p.images.length>1){
    document.getElementById('modalGalleryNav').innerHTML=p.images.map(function(img,i){return '<div class="modal-gallery-dot '+(i===0?'active':'')+'" onclick="document.getElementById(\'modalImage\').src=\''+img+'\'"></div>';}).join('');
  }
  modal.classList.add('open');
  document.body.style.overflow='hidden';
  switchTab('test');
}
function closeModal(){document.getElementById('productModal').classList.remove('open');document.body.style.overflow='';}
document.getElementById('productModal').addEventListener('click',function(e){if(e.target===e.currentTarget)closeModal();});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal();});
function switchTab(tab){
  var tabs = document.querySelectorAll('.modal-tab');
  var contents = document.querySelectorAll('.modal-tab-content');
  for(var i=0;i<tabs.length;i++){tabs[i].classList.remove('active');}
  for(var i=0;i<contents.length;i++){contents[i].classList.remove('active');}
  var activeTab = document.getElementById('tab-'+tab);
  if(activeTab) activeTab.classList.add('active');
  // Find tab button by index
  var tabNames = ['test','specs','reviews'];
  var tabIndex = tabNames.indexOf(tab);
  if(tabIndex >= 0 && tabs[tabIndex]) tabs[tabIndex].classList.add('active');
}
document.addEventListener('DOMContentLoaded',function(){renderProducts();renderTable();});
